name: marj_card_styles
description: A new Flutter package project.
version: 0.0.3

environment:
  sdk: ">=3.1.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  shimmer_animation: ^2.1.0+1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
