// Light and dark ColorSchemes made by FlexColorScheme v7.3.1.
// These ColorScheme objects require Flutter 3.7 or later.
import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class MARJTheme {
  static final _darkTheme = FlexThemeData.dark(
    colors: _colors.toDark(),
    surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
    blendLevel: 15,
    appBarStyle: FlexAppBarStyle.scaffoldBackground,
    darkIsTrueBlack: true,
    tooltipsMatchBackground: true,
    subThemesData: const FlexSubThemesData(
      blendOnLevel: 20,
      blendTextTheme: true,
      useTextTheme: true,
      useM2StyleDividerInM3: true,
      splashType: FlexSplashType.inkSparkle,
      textButtonRadius: 6.0,
      filledButtonRadius: 6.0,
      elevatedButtonRadius: 6.0,
      elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
      elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
      outlinedButtonRadius: 6.0,
      outlinedButtonBorderWidth: 0.5,
      outlinedButtonPressedBorderWidth: 1.0,
      toggleButtonsRadius: 6.0,
      toggleButtonsBorderWidth: 0.5,
      segmentedButtonRadius: 6.0,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonBorderWidth: 0.5,
      switchThumbFixedSize: true,
      unselectedToggleIsColored: true,
      sliderValueTinted: true,
      sliderTrackHeight: 2,
      inputDecoratorRadius: 6.0,
      inputDecoratorUnfocusedHasBorder: false,
      inputDecoratorFocusedBorderWidth: 0.5,
      fabUseShape: true,
      fabRadius: 6.0,
      fabSchemeColor: SchemeColor.tertiary,
      chipRadius: 6.0,
      cardRadius: 6.0,
      popupMenuRadius: 6.0,
      popupMenuElevation: 4.0,
      alignedDropdown: true,
      tooltipRadius: 6,
      tooltipWaitDuration: Duration(milliseconds: 300),
      tooltipShowDuration: Duration(milliseconds: 500),
      dialogElevation: 3.0,
      dialogRadius: 6.0,
      snackBarRadius: 6,
      tabBarIndicatorWeight: 1.5,
      tabBarDividerColor: Color(0x00000000),
      drawerRadius: 6.0,
      drawerIndicatorRadius: 6.0,
      drawerIndicatorSchemeColor: SchemeColor.primary,
      bottomSheetRadius: 6.0,
      bottomSheetElevation: 2.0,
      bottomSheetModalElevation: 3.0,
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.surfaceVariant,
      bottomNavigationBarShowUnselectedLabels: false,
      menuRadius: 6.0,
      menuElevation: 4.0,
      menuBarRadius: 6.0,
      menuBarElevation: 1.0,
      menuIndicatorRadius: 6.0,
      navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
      navigationBarUnselectedLabelSchemeColor: SchemeColor.onSurface,
      navigationBarSelectedIconSchemeColor: SchemeColor.onSurface,
      navigationBarUnselectedIconSchemeColor: SchemeColor.onSurface,
      navigationBarIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationBarIndicatorOpacity: 0.60,
      navigationBarIndicatorRadius: 6.0,
      navigationBarLabelBehavior:
          NavigationDestinationLabelBehavior.onlyShowSelected,
      navigationRailSelectedLabelSchemeColor: SchemeColor.onSurface,
      navigationRailUnselectedLabelSchemeColor: SchemeColor.onSurface,
      navigationRailSelectedIconSchemeColor: SchemeColor.onSurface,
      navigationRailUnselectedIconSchemeColor: SchemeColor.onSurface,
      navigationRailIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationRailIndicatorOpacity: 0.60,
      navigationRailIndicatorRadius: 6.0,
      navigationRailBackgroundSchemeColor: SchemeColor.surface,
      navigationRailLabelType: NavigationRailLabelType.none,
    ),
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
    ),
    tones: FlexTones.ultraContrast(Brightness.dark),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    swapLegacyOnMaterial3: true,
    fontFamily: GoogleFonts.poppins().fontFamily,
    typography: Typography.material2021(),
    textTheme: GoogleFonts.poppinsTextTheme(),
  );

  static final _lightTheme = FlexThemeData.light(
    colors: _colors,
    surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
    blendLevel: 22,
    appBarStyle: FlexAppBarStyle.background,
    bottomAppBarElevation: 1.0,
    lightIsWhite: true,
    tooltipsMatchBackground: true,
    subThemesData: const FlexSubThemesData(
      blendOnLevel: 10,
      blendOnColors: false,
      useTextTheme: true,
      useM2StyleDividerInM3: true,
      splashType: FlexSplashType.inkSparkle,
      textButtonRadius: 6.0,
      filledButtonRadius: 6.0,
      elevatedButtonRadius: 6.0,
      elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
      elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
      outlinedButtonRadius: 6.0,
      outlinedButtonBorderWidth: 0.5,
      outlinedButtonPressedBorderWidth: 1.0,
      toggleButtonsRadius: 6.0,
      toggleButtonsBorderWidth: 0.5,
      segmentedButtonRadius: 6.0,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonBorderWidth: 0.5,
      switchThumbFixedSize: true,
      unselectedToggleIsColored: true,
      sliderValueTinted: true,
      sliderTrackHeight: 2,
      inputDecoratorRadius: 6.0,
      inputDecoratorUnfocusedHasBorder: false,
      inputDecoratorFocusedBorderWidth: 0.5,
      fabUseShape: true,
      fabRadius: 6.0,
      fabSchemeColor: SchemeColor.tertiary,
      chipRadius: 6.0,
      cardRadius: 6.0,
      popupMenuRadius: 6.0,
      popupMenuElevation: 4.0,
      alignedDropdown: true,
      tooltipRadius: 6,
      tooltipWaitDuration: Duration(milliseconds: 300),
      tooltipShowDuration: Duration(milliseconds: 500),
      dialogElevation: 3.0,
      dialogRadius: 6.0,
      snackBarRadius: 6,
      tabBarIndicatorWeight: 1.5,
      tabBarDividerColor: Color(0x00000000),
      drawerRadius: 6.0,
      drawerIndicatorRadius: 6.0,
      drawerIndicatorSchemeColor: SchemeColor.primary,
      bottomSheetRadius: 6.0,
      bottomSheetElevation: 2.0,
      bottomSheetModalElevation: 3.0,
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.surfaceVariant,
      bottomNavigationBarShowUnselectedLabels: false,
      menuRadius: 6.0,
      menuElevation: 4.0,
      menuBarRadius: 6.0,
      menuBarElevation: 1.0,
      menuIndicatorRadius: 6.0,
      navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
      navigationBarUnselectedLabelSchemeColor: SchemeColor.onSurface,
      navigationBarSelectedIconSchemeColor: SchemeColor.onSurface,
      navigationBarUnselectedIconSchemeColor: SchemeColor.onSurface,
      navigationBarIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationBarIndicatorOpacity: 0.60,
      navigationBarIndicatorRadius: 6.0,
      navigationBarLabelBehavior:
          NavigationDestinationLabelBehavior.onlyShowSelected,
      navigationRailSelectedLabelSchemeColor: SchemeColor.onSurface,
      navigationRailUnselectedLabelSchemeColor: SchemeColor.onSurface,
      navigationRailSelectedIconSchemeColor: SchemeColor.onSurface,
      navigationRailUnselectedIconSchemeColor: SchemeColor.onSurface,
      navigationRailIndicatorSchemeColor: SchemeColor.secondaryContainer,
      navigationRailIndicatorOpacity: 0.60,
      navigationRailIndicatorRadius: 6.0,
      navigationRailBackgroundSchemeColor: SchemeColor.surface,
      navigationRailLabelType: NavigationRailLabelType.none,
    ),
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
      keepPrimary: true,
      keepSecondary: true,
      keepTertiary: true,
    ),
    tones: FlexTones.ultraContrast(Brightness.light)
        .onMainsUseBW()
        .onSurfacesUseBW(),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    swapLegacyOnMaterial3: true,
    fontFamily: GoogleFonts.poppins().fontFamily,
    typography: Typography.material2021(),
    textTheme: GoogleFonts.poppinsTextTheme(),
  );

  static ThemeData get light => _lightTheme;

  static ThemeData get dark => _darkTheme;

  static ThemeData defTheme(ThemeMode mode) =>
      mode == ThemeMode.dark ? dark : light;

  static FlexSchemeColor get _colors => const FlexSchemeColor(
        primary: Color(0xff3562cc),
        primaryContainer: Color(0xff86a9fe),
        secondary: Color(0xff5675bd),
        secondaryContainer: Color(0xff9dafd8),
        tertiary: Color(0xff384666),
        tertiaryContainer: Color(0xff8899c0),
        appBarColor: Color(0xff9dafd8),
        error: Color(0xffb00020),
      );
}
